version: '3.8'

services:
  coding-agent:
    build: .
    container_name: ai-coding-agent
    privileged: false
    ports:
       - "127.0.0.1:7860:7860"
    environment:
      - GRADIO_HOST=0.0.0.0
      - GRADIO_PORT=7860
      - GRADIO_SHARE=false
      - GRADIO_ANALYTICS_ENABLED=False
      - GRADIO_TELEMETRY_ENABLED=False
      - ALLOW_LOCAL_EXECUTION=False
    volumes:
      - ./.env:/app/.env:ro
    restart: unless-stopped
    tmpfs:
      - /tmp
      - /app/.gradio
    dns:
      - 1.1.1.1
      - 8.8.8.8
      - 8.8.4.4
    security_opt:
      - no-new-privileges:true

networks:
  research-network:
    driver: bridge
    internal: false
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: "true" 